

select * into bkp_PB_ORACLEFIN_MERGE_20180805 from PB_ORACLEFIN_MERGE
select * into bkp_PB_ORACLEFIN_APTRANS_20180805 from PB_ORACLEFIN_APTRANS
select * into bkp_PB_ORACLEFIN_ARTRANS_20180805 from PB_ORACLEFIN_ARTRANS
select * into bkp_PB_ORACLEFIN_INVTRANS_20180805 from PB_ORACLEFIN_INVTRANS
select * into bkp_PB_ORACLEFIN_TRANS_20180805 from PB_ORACLEFIN_TRANS



select distinct year
from PB_ORACLEFIN_MERGE



u/pdate PB_ORACLEFIN_MERGE
set year = (year + 1)

