# JD - 25/10/2018
FROM ubuntu
RUN apt-get update
RUN apt-get full-upgrade -y

RUN apt-get install git -y
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip3 install gist

# docker cp pi.py f646a98901c0:/pi.py ???????????????????????
